steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
      - '--update-secrets PORT=HALY_MASTER_PORT,SLACK_BOT_TOKEN=HALY_MASTER_SLACK_BOT_TOKEN,SLACK_SIGNING_SECRET=HALY_MASTER_SLACK_SIGNING_SECRET,OPEN_API_KEY=HALY_MASTER_OPEN_API_KEY'
      - '--region=us-central1'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
options:
  substitutionOption: ALLOW_LOOSE
  logging: NONE
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: haly-master
  _DEPLOY_REGION: us-central1
tags:
  - haly-master
