steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: 'gcr.io/cloud-builders/bandit'
    args:
      - '-r'
      - '.'
      - '-lll'
      - '-s'
      - 'B,H'
    id: Security
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
      - '--update-secrets=SLACK_BOT_TOKEN=HALY_MASTER_SLACK_BOT_TOKEN:latest,SLACK_SIGNING_SECRET=HALY_MASTER_SLACK_SIGNING_SECRET:latest,OPENAI_API_KEY=HALY_MASTER_OPEN_API_KEY:latest'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--min-instances=2'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: haly-master
tags:
  - haly-master
