steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/slack-bot/haly:$SHORT_HASH-dev', '.' ]
images:
- 'us-docker.pkg.dev/$PROJECT_ID/slack-bot/haly:$SHORT_HASH-dev'

options:
  logging: CLOUD_LOGGING_ONLY
