name: Bandit Security Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r src/
